import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("static HTML contains the La Taverna website", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");

  assert.match(html, /^<!doctype html>/i);
  assert.match(html, /<title>La Taverna di Monterosso \| Ristorante a Monterosso al Mare<\/title>/i);
  assert.match(html, /href="site\.css"/);
  assert.match(html, /src="site\.js"/);
  assert.match(html, /assets\/hero-wine-desktop\.jpg/);
  assert.match(html, /assets\/hero-wine-mobile\.jpg/);
  assert.match(html, /LANTERNA/);
  assert.match(html, /brand-fish/);
  assert.match(html, /brand-fish-outline/);
  assert.match(html, /hero-title-mobile">LA LANTERNA/);
  assert.match(html, /restaurant-mobile-copy/);
  assert.match(html, /Cucina italiana, pesce e sapori liguri nel cuore di Monterosso/);
  assert.match(html, /class="hero-socials"/);
  assert.match(html, /class="contact-socials"/);
  assert.match(html, /class="footer-socials"/);
  assert.match(html, /https:\/\/www\.instagram\.com\/ristorante_la_taverna_5_terre\//);
  assert.match(html, /https:\/\/www\.facebook\.com\/p\/La-Taverna-di-Monterosso-100054517236999\/\?locale=it_IT/);
  assert.match(html, /assets\/location-01\.jpg/);
  assert.match(html, /assets\/location-03\.png/);
  assert.match(html, /assets\/location-04\.png/);
  assert.match(html, /assets\/food-01\.png/);
  assert.match(html, /assets\/food-02\.png/);
  assert.match(html, /assets\/food-03\.jpg/);
  assert.match(html, /assets\/food-04\.png/);
  assert.match(html, /assets\/food-05\.jpg/);
  assert.match(html, /assets\/food-06\.jpg/);
  assert.match(html, /La Taverna di Monterosso/);
  assert.match(html, /Ristorante · Pizzeria/);
  assert.match(html, /Monterosso al Mare/);
  assert.match(html, /Via Molinelli 39/);
  assert.match(html, /\+39 0187 829111/);
  assert.match(html, /ristorante-lataverna@libero\.it/);
  assert.match(html, /data-food-track/);
  assert.match(html, /data-location-track/);
  assert.match(html, /data-location-current>01<\/span> \/ 03/);
  assert.match(html, /class="map-frame"/);
  assert.match(html, /z=18/);
  assert.match(html, /contacts\.openMap/);
  assert.match(html, /Tripadvisor/);
  assert.match(html, /tripadvisor-badge/);
  assert.match(html, /APenkKm7iecQ4G6P-TsbSMFKIQtv3EFIqRAFw-i8uEbk55Z-_yRul-XFMTpOS7cDGlyVhxznpQymVQg9Z1VkTqdUo_kwnaK6V-cuEp8ASwweiJjtkN_PiraW2VJgc9c4cWdlL_EkMNmn7Ra8pjfpGcDb2d9X6_QSIw%3D%3D/);
  assert.match(html, /data-card-modal/);
  assert.match(html, /data-booking-modal/);
  assert.match(html, /whatsapp-cta-icon/);
  assert.match(html, /whatsapp-icon-chat/);
  assert.match(html, /whatsapp-icon-phone/);
  assert.match(html, /tripadvisor-owl/);
  assert.match(html, /owl-pupil/);
  assert.match(html, /reviews-title-mobile/);
  assert.match(html, /contact-title-mobile/);
  assert.match(html, /Gamberi rossi freschi serviti su ghiaccio/);
  assert.match(html, /Spaghetti alle vongole serviti in piatto bianco/);
  assert.match(html, /Dessert al cucchiaio con crema e salsa gialla/);
  assert.match(html, /Tavolo apparecchiato de La Taverna/);
  assert.doesNotMatch(html, /Costata alla griglia|La brace/);
  assert.doesNotMatch(html, /Grigliata mista|Piatto al cartoccio|Sala de La Taverna con tavoli/);
  assert.doesNotMatch(html, /assets\/hero-entrance-desktop\.jpg|assets\/hero-entrance-mobile\.jpg/);
  assert.doesNotMatch(html, /assets\/food-05\.png|assets\/food-06\.png|assets\/location-01\.png/);
  assert.doesNotMatch(html, /assets\/brand-la-taverna\.png|whatsapp-icon-bg|whatsapp-icon-ring/);
  assert.doesNotMatch(html, /assets\/location-02\.png/);
  assert.doesNotMatch(html, /assets\/food-03\.png/);
  assert.doesNotMatch(html, /Your site is taking shape|codex-preview|SkeletonPreview|react-loading-skeleton|\/assets\/index-/i);
});

test("static assets are self-contained and scoped", async () => {
  const [css, script, favicon] = await Promise.all([
    readFile(new URL("../site.css", import.meta.url), "utf8"),
    readFile(new URL("../site.js", import.meta.url), "utf8"),
    readFile(new URL("../favicon.svg", import.meta.url), "utf8"),
  ]);

  assert.match(css, /\.image-placeholder/);
  assert.match(css, /background:\s*#000/);
  assert.match(css, /--gold:\s*#b88746/);
  assert.match(css, /--gold-light:\s*#f0cf8a/);
  assert.match(css, /--orange:\s*#d6a545/);
  assert.match(css, /\.hero-picture/);
  assert.match(css, /brightness\(1\.22\)/);
  assert.match(css, /object-position:\s*center center/);
  assert.match(css, /\.whatsapp-cta-icon/);
  assert.match(css, /whatsapp-icon-chat/);
  assert.match(css, /@keyframes whatsappChatBreath/);
  assert.match(css, /@keyframes whatsappPhoneTilt/);
  assert.match(css, /\.brand-mark/);
  assert.match(css, /brand-fish-outline/);
  assert.match(css, /\.restaurant-section\s+\.heading-copy p:not\(\.restaurant-mobile-copy\)\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /\.reviews-title-mobile/);
  assert.match(css, /\.contact-title-mobile/);
  assert.match(css, /\.rating-block\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /\.review-card > p\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /\.contact-list > div:nth-child\(4\)\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /\.contact-socials\s*\{[\s\S]*display:\s*flex/);
  assert.match(css, /\.map-label\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /\.footer-socials\s*\{[\s\S]*display:\s*flex/);
  assert.match(css, /flex-direction:\s*column/);
  assert.match(css, /white-space:\s*nowrap/);
  assert.match(css, /padding-bottom:\s*calc\(5\.35rem \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(css, /\.hero-primary\s*\{[\s\S]*position:\s*fixed/);
  assert.match(css, /bottom:\s*max\(1rem,\s*env\(safe-area-inset-bottom\)\)/);
  assert.match(css, /\.hero-secondary\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /@keyframes owlBlink/);
  assert.match(css, /@keyframes owlBadgeFloat/);
  assert.match(css, /#8f6530/);
  assert.doesNotMatch(css, /#1fbf62|whatsapp-icon-bg|whatsapp-icon-ring/);
  assert.doesNotMatch(css, /review-links-summary a:hover[\s\S]{0,220}background:\s*var\(--ink\)/);
  assert.match(css, /\.map-frame/);
  assert.match(css, /saturate\(1\.18\)/);
  assert.match(css, /@import url\("https:\/\/fonts\.googleapis\.com/);
  assert.match(script, /whatsappNumber = "393899215920"/);
  assert.match(script, /https:\/\/wa\.me\/\$\{whatsappNumber\}/);
  assert.match(script, /setupCarousel/);
  assert.match(favicon, /<svg/);
  assert.doesNotMatch(css, /hero-verve|dish-0|location-0|_sites-preview|codex-preview/i);
  assert.doesNotMatch(script, /Verve|393465874048|mailto:\$\{contactEmail\}/i);
});
