import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("static HTML contains the La Taverna website", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");

  assert.match(html, /^<!doctype html>/i);
  assert.match(html, /<html class="notranslate" lang="it" translate="no">/);
  assert.match(html, /<body class="notranslate" translate="no">/);
  assert.match(html, /<meta name="google" content="notranslate" \/>/);
  assert.match(html, /<meta name="robots" content="notranslate" \/>/);
  assert.match(html, /<title>La Taverna di Monterosso \| Ristorante a Monterosso al Mare<\/title>/i);
  assert.match(html, /href="site\.css"/);
  assert.match(html, /src="site\.js"/);
  assert.match(html, /assets\/hero-wine-desktop\.jpg/);
  assert.match(html, /assets\/hero-wine-desktop-2x\.jpg/);
  assert.match(html, /assets\/hero-wine-mobile\.jpg/);
  assert.match(html, /LANTERNA/);
  assert.match(html, /brand-fish/);
  assert.match(html, /brand-fish-tail/);
  assert.match(html, /brand-fish-outline/);
  assert.doesNotMatch(html, /brand-fish-fin/);
  assert.match(html, /hero-title-mobile">LA LANTERNA/);
  assert.match(html, /restaurant-mobile-copy/);
  assert.match(html, /Cucina italiana, pesce e sapori liguri nel cuore di Monterosso/);
  assert.match(html, /class="hero-socials"/);
  assert.match(html, /class="contact-socials"/);
  assert.match(html, /class="footer-socials"/);
  assert.match(html, /class="footer-social-link"/);
  assert.match(html, /data-i18n="reviews\.title">Cosa dicono di noi/);
  assert.match(html, /data-i18n="contacts\.title">Contatti/);
  assert.match(html, /https:\/\/www\.instagram\.com\/ristorante_la_taverna_5_terre\//);
  assert.match(html, /https:\/\/www\.facebook\.com\/p\/La-Taverna-di-Monterosso-100054517236999\/\?locale=it_IT/);
  assert.match(html, /assets\/location-01\.jpg/);
  assert.match(html, /assets\/location-03\.png/);
  assert.match(html, /assets\/location-04\.png/);
  assert.match(html, /assets\/food-01\.png/);
  assert.match(html, /assets\/food-02\.png/);
  assert.match(html, /assets\/food-03\.jpg/);
  assert.match(html, /assets\/food-04\.png/);
  assert.match(html, /assets\/food-05\.jpg/);
  assert.match(html, /assets\/food-06\.jpg/);
  assert.match(html, /La Taverna di Monterosso/);
  assert.match(html, /Ristorante · Pizzeria/);
  assert.match(html, /Monterosso al Mare/);
  assert.match(html, /Via Molinelli 39/);
  assert.match(html, /\+39 0187 829111/);
  assert.match(html, /ristorante-lataverna@libero\.it/);
  assert.match(html, /data-food-track/);
  assert.match(html, /data-location-track/);
  assert.match(html, /data-location-current>01<\/span> \/ 03/);
  assert.match(html, /class="map-frame"/);
  assert.match(html, /z=18/);
  assert.match(html, /contacts\.openMap/);
  assert.match(html, /Tripadvisor/);
  assert.match(html, /tripadvisor-badge/);
  assert.match(html, /APenkKm7iecQ4G6P-TsbSMFKIQtv3EFIqRAFw-i8uEbk55Z-_yRul-XFMTpOS7cDGlyVhxznpQymVQg9Z1VkTqdUo_kwnaK6V-cuEp8ASwweiJjtkN_PiraW2VJgc9c4cWdlL_EkMNmn7Ra8pjfpGcDb2d9X6_QSIw%3D%3D/);
  assert.match(html, /data-card-modal/);
  assert.match(html, /data-booking-modal/);
  assert.match(html, /whatsapp-cta-icon/);
  assert.match(html, /viewBox="0 0 32 32"/);
  assert.match(html, /whatsapp-icon-chat/);
  assert.match(html, /whatsapp-icon-phone/);
  assert.match(html, /class="mobile-sticky-book"/);
  assert.match(html, /data-i18n="form\.time">Orario/);
  assert.match(html, /<input type="time" name="time"/);
  assert.match(html, /tripadvisor-owl/);
  assert.match(html, /owl-pupil/);
  assert.match(html, /Gamberi rossi freschi serviti su ghiaccio/);
  assert.match(html, /Spaghetti alle vongole serviti in piatto bianco/);
  assert.match(html, /Dessert al cucchiaio con crema e salsa gialla/);
  assert.match(html, /Tavolo apparecchiato de La Taverna/);
  assert.doesNotMatch(html, /Costata alla griglia|La brace/);
  assert.doesNotMatch(html, /Grigliata mista|Piatto al cartoccio|Sala de La Taverna con tavoli/);
  assert.doesNotMatch(html, /assets\/hero-entrance-desktop\.jpg|assets\/hero-entrance-mobile\.jpg/);
  assert.doesNotMatch(html, /assets\/food-05\.png|assets\/food-06\.png|assets\/location-01\.png/);
  assert.doesNotMatch(html, /assets\/brand-la-taverna\.png|whatsapp-icon-bg|whatsapp-icon-ring/);
  assert.doesNotMatch(html, /assets\/location-02\.png/);
  assert.doesNotMatch(html, /assets\/food-03\.png/);
  assert.doesNotMatch(html, /contacts\.socialLabel|latavernadimonterosso\.eatbu\.com/);
  assert.doesNotMatch(html, /class="hero-secondary"|M20\.15 11\.85|Orario, richieste|rating-block|Recensioni aggiornate|reviews-title-mobile|contact-title-mobile|★/);
  assert.doesNotMatch(html, /Your site is taking shape|codex-preview|SkeletonPreview|react-loading-skeleton|\/assets\/index-/i);
});

test("static assets are self-contained and scoped", async () => {
  const [css, script, favicon] = await Promise.all([
    readFile(new URL("../site.css", import.meta.url), "utf8"),
    readFile(new URL("../site.js", import.meta.url), "utf8"),
    readFile(new URL("../favicon.svg", import.meta.url), "utf8"),
  ]);

  assert.match(css, /\.image-placeholder/);
  assert.match(css, /background:\s*#000/);
  assert.match(css, /--gold:\s*#b88746/);
  assert.match(css, /--gold-light:\s*#f0cf8a/);
  assert.match(css, /--orange:\s*#d6a545/);
  assert.match(css, /\.hero-picture/);
  assert.match(css, /brightness\(1\.22\)/);
  assert.match(css, /object-position:\s*center center/);
  assert.match(css, /\.whatsapp-cta-icon/);
  assert.match(css, /whatsapp-icon-chat/);
  assert.match(css, /\.whatsapp-cta-icon \.whatsapp-icon-phone\s*\{[\s\S]*fill:\s*currentColor[\s\S]*stroke:\s*none/);
  assert.match(css, /Final requested desktop and icon corrections/);
  assert.match(css, /Final requested desktop and icon corrections[\s\S]*\.whatsapp-cta-icon\s*\{[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /Final monochrome detail trial and cross-device tuning/);
  assert.match(css, /-webkit-text-size-adjust:\s*100%/);
  assert.match(css, /text-size-adjust:\s*100%/);
  assert.match(css, /\.hero :where\(\.hero-overline, \.hero-hours, \.hero-hours span, \.hero-edge, \.scroll-cue, \.hero-social-link\)\s*\{[\s\S]*color:\s*var\(--white\)/);
  assert.match(css, /\.location-section :where\(\.section-kicker, \.location-card figcaption, \.carousel-footer > p\),[\s\S]*\.contact-section :where\(\.section-kicker, \.contact-list h3, \.contact-list a, \.contact-list p, \.contact-social-link\)\s*\{[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /\.site-footer\s*\{[\s\S]*padding:\s*clamp\(2\.1rem,\s*3\.2vw,\s*3\.15rem\)/);
  assert.match(css, /Final compact footer pass/);
  assert.match(css, /@media \(min-width:\s*761px\)[\s\S]*\.site-footer\s*\{[\s\S]*padding:\s*1\.55rem var\(--page-x\) 0\.8rem/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.site-footer\s*\{[\s\S]*padding:\s*1\.55rem var\(--page-x\) 1rem/);
  assert.match(css, /@supports \(height:\s*100dvh\)/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.hero-overline\s*\{[\s\S]*display:\s*block/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.hero-edge\s*\{[\s\S]*display:\s*block/);
  assert.match(css, /@keyframes whatsappChatBreath/);
  assert.match(css, /@keyframes whatsappPhoneTilt/);
  assert.match(css, /\.brand-mark/);
  assert.match(css, /brand-fish-tail/);
  assert.match(css, /brand-fish-outline/);
  assert.match(css, /\.restaurant-section\s+\.heading-copy p:not\(\.restaurant-mobile-copy\)\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /\.rating-block\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /\.review-card > p\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /\.contact-list > div:nth-child\(4\)\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /\.contact-socials\s*\{[\s\S]*display:\s*flex/);
  assert.match(css, /\.map-label\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /\.footer-socials\s*\{[\s\S]*display:\s*flex/);
  assert.match(css, /\.footer-social-link/);
  assert.match(css, /flex:\s*0 0 min\(88vw,\s*24rem\)/);
  assert.match(css, /height:\s*22\.25rem/);
  assert.match(css, /saturate\(1\.28\)/);
  assert.match(css, /flex-direction:\s*column/);
  assert.match(css, /white-space:\s*nowrap/);
  assert.match(css, /padding-bottom:\s*calc\(5\.35rem \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(css, /\.mobile-sticky-book\s*\{[\s\S]*position:\s*fixed/);
  assert.match(css, /\.hero-actions,\s*\.hero-primary\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /brightness\(1\.32\)/);
  assert.match(css, /brightness\(1\.4\)/);
  assert.match(css, /bottom:\s*max\(1rem,\s*env\(safe-area-inset-bottom\)\)/);
  assert.match(css, /\.hero-secondary\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /@keyframes owlBlink/);
  assert.match(css, /@keyframes owlBadgeFloat/);
  assert.match(css, /#8f6530/);
  assert.match(css, /Final requested desktop and icon corrections[\s\S]*\.reviews-intro > div:first-child\s*\{[\s\S]*text-align:\s*left/);
  assert.match(css, /Final requested desktop and icon corrections[\s\S]*\.review-links-summary a\s*\{[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /Final requested desktop and icon corrections[\s\S]*\.tripadvisor-badge \.owl-pupil\s*\{[\s\S]*fill:\s*var\(--ink\)/);
  assert.doesNotMatch(css, /#1fbf62|whatsapp-icon-bg|whatsapp-icon-ring/);
  assert.doesNotMatch(css, /review-links-summary a:hover[\s\S]{0,220}background:\s*var\(--ink\)/);
  assert.match(css, /\.map-frame/);
  assert.match(css, /saturate\(1\.18\)/);
  assert.match(css, /@import url\("https:\/\/fonts\.googleapis\.com/);
  assert.match(script, /whatsappNumber = "393899215920"/);
  assert.match(script, /"reviews\.title": "Cosa dicono di noi"/);
  assert.match(script, /"contacts\.title": "Contatti"/);
  assert.match(script, /"form\.time": "Orario"/);
  assert.match(script, /Ciao La Taverna, sono \$\{name\} e vorrei prenotare un tavolo/);
  assert.match(script, /per il giorno \$\{formattedDate\}/);
  assert.match(script, /alle \$\{time\}/);
  assert.match(script, /https:\/\/wa\.me\/\$\{whatsappNumber\}/);
  assert.match(script, /setupCarousel/);
  assert.match(favicon, /<svg/);
  assert.doesNotMatch(css, /hero-verve|dish-0|location-0|_sites-preview|codex-preview/i);
  assert.doesNotMatch(script, /Verve|393465874048|mailto:\$\{contactEmail\}|Richiesta:|Request:|Data:|Guests:|Recensioni aggiornate|Updated reviews/i);
});
