import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("static HTML contains the La Taverna website", async () => {
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");

  assert.match(html, /^<!doctype html>/i);
  assert.match(html, /<html class="notranslate" lang="it" translate="no">/);
  assert.match(html, /<body class="notranslate" translate="no">/);
  assert.match(html, /<meta name="google" content="notranslate" \/>/);
  assert.match(html, /<meta name="robots" content="notranslate" \/>/);
  assert.match(html, /<title>La Taverna di Monterosso \| Ristorante a Monterosso al Mare<\/title>/i);
  assert.match(html, /href="site\.css"/);
  assert.match(html, /src="site\.js"/);
  assert.match(html, /assets\/hero-wine-desktop\.jpg/);
  assert.match(html, /assets\/hero-wine-desktop-2x\.jpg/);
  assert.match(html, /assets\/hero-wine-mobile\.jpg/);
  assert.match(html, /class="hero-image"[\s\S]*alt=""/);
  assert.match(html, /class="hero-image"[\s\S]*aria-hidden="true"/);
  assert.doesNotMatch(html, /Facciata in pietra de La Taverna di Monterosso/);
  assert.match(html, /header-brand-mark/);
  assert.match(html, /assets\/brand-la-taverna-logo\.png/);
  assert.match(html, /alt="La Taverna"/);
  assert.match(html, /card-brand-mark/);
  assert.match(html, /card-brand-mark[\s\S]*assets\/brand-la-taverna-logo\.png/);
  assert.match(html, /class="footer-logo"[\s\S]*>La Taverna<\/a>/);
  assert.match(html, /Scopri il nostro menù/);
  assert.match(html, /Menù/);
  assert.match(html, /convivialità/);
  assert.match(html, /phone-line-icon/);
  assert.doesNotMatch(html, /LANTERNA|Lanterna, torna|brand-fish-tail|brand-fish-outline/);
  assert.doesNotMatch(html, /convivialita|Scopri il nostro menu|Il nostro<br \/><em>menu\.<\/em>/);
  assert.match(html, /hero-title-mobile">LA TAVERNA/);
  assert.match(html, /restaurant-mobile-copy/);
  assert.match(html, /Cucina italiana, pesce e sapori liguri nel cuore di Monterosso/);
  assert.match(html, /class="hero-socials"/);
  assert.doesNotMatch(html, /class="contact-socials"|class="contact-social-link"/);
  assert.match(html, /class="contact-phone-cell"/);
  assert.match(html, /class="contact-phone-row"/);
  assert.match(html, /class="footer-socials"/);
  assert.match(html, /class="footer-social-link"/);
  assert.match(html, /data-i18n="reviews\.title">Cosa dicono di noi/);
  assert.match(html, /data-i18n="contacts\.title">Contatti/);
  assert.match(html, /https:\/\/www\.instagram\.com\/ristorante_la_taverna_5_terre\//);
  assert.match(html, /https:\/\/www\.facebook\.com\/p\/La-Taverna-di-Monterosso-100054517236999\/\?locale=it_IT/);
  assert.match(html, /assets\/location-01\.jpg/);
  assert.match(html, /assets\/location-03\.png/);
  assert.match(html, /assets\/location-04\.png/);
  assert.match(html, /assets\/location-04\.png[\s\S]*assets\/location-exterior-terrace\.png/);
  assert.match(html, /data-i18n="location\.exterior">L'esterno/);
  assert.match(html, /assets\/food-01\.png/);
  assert.match(html, /assets\/food-02\.png/);
  assert.match(html, /assets\/food-03\.jpg/);
  assert.match(html, /assets\/food-04\.png/);
  assert.match(html, /assets\/food-05\.jpg/);
  assert.match(html, /assets\/food-06\.jpg/);
  assert.match(html, /La Taverna di Monterosso/);
  assert.match(html, /Ristorante - Pizzeria/);
  assert.match(html, /Monterosso al Mare/);
  assert.match(html, /Via Molinelli 39/);
  assert.match(html, /\+39 0187 829111/);
  assert.match(html, /ristorante-lataverna@libero\.it/);
  assert.match(html, /data-food-track/);
  assert.match(html, /data-location-track/);
  assert.match(html, /data-location-current>01<\/span> \/ 04/);
  assert.match(html, /class="map-frame"/);
  assert.match(html, /z=18/);
  assert.match(html, /contacts\.openMap/);
  assert.match(html, /Tripadvisor/);
  assert.match(html, /tripadvisor-badge/);
  assert.match(html, /APenkKm7iecQ4G6P-TsbSMFKIQtv3EFIqRAFw-i8uEbk55Z-_yRul-XFMTpOS7cDGlyVhxznpQymVQg9Z1VkTqdUo_kwnaK6V-cuEp8ASwweiJjtkN_PiraW2VJgc9c4cWdlL_EkMNmn7Ra8pjfpGcDb2d9X6_QSIw%3D%3D/);
  assert.match(html, /data-card-modal/);
  assert.match(html, /data-booking-modal/);
  assert.match(html, /whatsapp-cta-icon/);
  assert.match(html, /viewBox="0 0 24 24"/);
  assert.match(html, /whatsapp-icon-mark/);
  assert.match(html, /M17\.472 14\.382c-/);
  assert.doesNotMatch(html, /viewBox="0 0 32 32"|whatsapp-icon-chat|whatsapp-icon-phone/);
  assert.match(html, /class="mobile-sticky-book"/);
  assert.match(html, /data-i18n="form\.time">Orario/);
  assert.match(html, /<input type="time" name="time"/);
  assert.match(html, /tripadvisor-owl/);
  assert.match(html, /owl-pupil/);
  assert.match(html, /owl-no-speak/);
  assert.match(html, /owl-no-hear/);
  assert.match(html, /owl-no-see/);
  assert.match(html, /owl-gesture/);
  assert.match(html, /Gamberi rossi freschi serviti su ghiaccio/);
  assert.match(html, /Spaghetti alle vongole serviti in piatto bianco/);
  assert.match(html, /Dessert al cucchiaio con crema e salsa gialla/);
  assert.match(html, /Tavolo apparecchiato de La Taverna/);
  assert.doesNotMatch(html, /Costata alla griglia|La brace/);
  assert.doesNotMatch(html, /Grigliata mista|Piatto al cartoccio|Sala de La Taverna con tavoli/);
  assert.doesNotMatch(html, /assets\/hero-entrance-desktop\.jpg|assets\/hero-entrance-mobile\.jpg/);
  assert.doesNotMatch(html, /assets\/food-05\.png|assets\/food-06\.png|assets\/location-01\.png/);
  assert.doesNotMatch(html, /assets\/brand-la-taverna\.png|assets\/brand-la-taverna-header-v2\.png|assets\/brand-la-taverna-2026-light\.png|assets\/brand-la-taverna-2026-ink\.png|footer-brand-mark|whatsapp-icon-bg|whatsapp-icon-ring/);
  assert.doesNotMatch(html, /assets\/location-02\.png/);
  assert.doesNotMatch(html, /assets\/food-03\.png/);
  assert.doesNotMatch(html, /contacts\.socialLabel|latavernadimonterosso\.eatbu\.com/);
  assert.doesNotMatch(html, /class="hero-secondary"|M20\.15 11\.85|Orario, richieste|rating-block|Recensioni aggiornate|reviews-title-mobile|contact-title-mobile|★/);
  assert.doesNotMatch(html, /Your site is taking shape|codex-preview|SkeletonPreview|react-loading-skeleton|\/assets\/index-/i);
});

test("static assets are self-contained and scoped", async () => {
  const [css, script, favicon] = await Promise.all([
    readFile(new URL("../site.css", import.meta.url), "utf8"),
    readFile(new URL("../site.js", import.meta.url), "utf8"),
    readFile(new URL("../favicon.svg", import.meta.url), "utf8"),
  ]);

  assert.match(css, /\.image-placeholder/);
  assert.match(css, /background:\s*#000/);
  assert.match(css, /--gold:\s*#b88746/);
  assert.match(css, /--gold-light:\s*#f0cf8a/);
  assert.match(css, /--orange:\s*#d6a545/);
  assert.match(css, /\.hero-picture/);
  assert.match(css, /Definitive requested Aug 6 corrections/);
  assert.match(css, /background-image:\s*url\("assets\/hero-wine-desktop\.jpg"\)/);
  assert.match(css, /brightness\(1\.22\)/);
  assert.match(css, /object-position:\s*center center/);
  assert.match(css, /\.whatsapp-cta-icon/);
  assert.match(css, /whatsapp-icon-mark/);
  assert.match(css, /-webkit-text-size-adjust:\s*100%/);
  assert.match(css, /text-size-adjust:\s*100%/);
  assert.match(css, /\.hero :where\(\.hero-overline, \.hero-hours, \.hero-hours span, \.hero-edge, \.scroll-cue, \.hero-social-link\)\s*\{[\s\S]*color:\s*var\(--white\)/);
  assert.match(css, /\.location-section :where\(\.section-kicker, \.location-card figcaption, \.carousel-footer > p\),[\s\S]*\.contact-section :where\(\.section-kicker, \.contact-list h3, \.contact-list a, \.contact-list p, \.contact-social-link\)\s*\{[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /@keyframes whatsappChatBreath/);
  assert.match(css, /@keyframes whatsappPhoneTilt/);
  assert.match(css, /\.brand-mark/);
  assert.match(css, /brand-fish-body/);
  assert.match(css, /brand-fish-fin/);
  assert.match(css, /\.card-brand-mark/);
  assert.match(css, /owlPremiumFloat/);
  assert.match(css, /owlSpeakCover/);
  assert.match(css, /owlHearLeft/);
  assert.match(css, /owlSeeCover/);
  assert.match(css, /\.contact-list > div:nth-child\(2\)\s*\{[\s\S]*border-right:\s*1px solid/);
  assert.match(css, /@media \(min-width:\s*761px\)[\s\S]*\.footer-main\s*\{[\s\S]*flex-direction:\s*column/);
  assert.match(css, /Definitive requested Aug 6 corrections[\s\S]*\.hero-image\s*\{[\s\S]*brightness\(0\.92\)/);
  assert.match(css, /Definitive requested Aug 6 corrections[\s\S]*\.card-modal :where\(\.section-kicker, \.card-intro h2 em, \.catalog-section h3, \.catalog-item > span\)\s*\{[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /Definitive requested Aug 6 corrections[\s\S]*\.reviews-intro > div:first-child,[\s\S]*\.reviews-intro h2\s*\{[\s\S]*text-align:\s*center/);
  assert.match(css, /\.whatsapp-icon-mark\s*\{[\s\S]*fill:\s*currentColor[\s\S]*stroke:\s*none/);
  assert.match(css, /\.contact-socials\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /Definitive black and white detail pass/);
  assert.match(css, /\.mobile-menu \.menu-book\s*\{[\s\S]*background:\s*var\(--white\)[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /body \.mobile-sticky-book\.is-on-light\s*\{[\s\S]*background:\s*var\(--ink\)[\s\S]*color:\s*var\(--white\)/);
  assert.match(css, /\.tripadvisor-badge \.owl-frame\s*\{[\s\S]*stroke-width:\s*2\.05/);
  assert.match(css, /\.site-header \.brand-mark/);
  assert.match(css, /Final brand image and no-gold corrections/);
  assert.match(css, /\.site-header \.header-brand-mark\s*\{[\s\S]*width:\s*clamp/);
  assert.match(css, /--accent-gold-bright:\s*var\(--ink\)/);
  assert.match(css, /@media \(min-width:\s*761px\)[\s\S]*\.hero \.hero-socials\s*\{[\s\S]*right:\s*var\(--page-x\)[\s\S]*left:\s*auto[\s\S]*transform:\s*none/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.hero \.hero-socials\s*\{[\s\S]*bottom:\s*1rem/);
  assert.match(css, /Final mobile hero and contact cleanup/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.hero h1\s*\{[\s\S]*white-space:\s*nowrap/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.hero-overline\s*\{[\s\S]*order:\s*1/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.hero-address\s*\{[\s\S]*order:\s*3/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.hero-hours,[\s\S]*\.hero-actions\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.hero-edge\s*\{[\s\S]*display:\s*block/);
  assert.match(css, /Final screenshot fixes/);
  assert.match(css, /\.hero-image\s*\{[\s\S]*color:\s*transparent[\s\S]*font-size:\s*0/);
  assert.match(css, /@media \(min-width:\s*761px\)[\s\S]*\.contact-section \.contact-actions \.contact-book\s*\{[\s\S]*background:\s*var\(--paper\)[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.footer-main\s*\{[\s\S]*flex-direction:\s*column/);
  assert.match(css, /\.footer-socials/);
  assert.match(css, /\.footer-social-link/);
  assert.match(css, /flex-direction:\s*column/);
  assert.match(css, /white-space:\s*nowrap/);
  assert.match(css, /Final mobile-only polish pass/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.site-header\s*\{[\s\S]*min-height:\s*4\.35rem/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.hero-overline\s*\{[\s\S]*order:\s*1[\s\S]*margin:\s*0 0 0\.72rem/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.hero-edge-left\s*\{[\s\S]*transform:\s*translateY\(-50%\) rotate\(180deg\)/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.mobile-sticky-book\s*\{[\s\S]*bottom:\s*calc\(1rem \+ env\(safe-area-inset-bottom\)\)[\s\S]*border-radius:\s*6px/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.review-awards > span\s*\{[\s\S]*display:\s*none/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.tripadvisor-badge b,[\s\S]*\.tripadvisor-badge \.tripadvisor-owl\s*\{[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.contact-section \.contact-actions \.contact-book\s*\{[\s\S]*background:\s*var\(--paper\)[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /Final brand replacement, location exterior, and desktop hero edge pass/);
  assert.match(css, /Post-screenshot logo fix and final mobile header pass/);
  assert.match(css, /\.site-header \.brand-logo-img,[\s\S]*\.card-brand-mark \.brand-logo-img\s*\{[\s\S]*filter:\s*none/);
  assert.match(css, /\.location-card:nth-child\(4\) img\s*\{[\s\S]*object-position:\s*center center/);
  assert.match(css, /@media \(min-width:\s*761px\)[\s\S]*\.hero-edge\s*\{[\s\S]*top:\s*50%[\s\S]*\.hero-edge-left\s*\{[\s\S]*transform:\s*translateY\(-50%\) rotate\(180deg\)[\s\S]*\.hero-edge-right\s*\{[\s\S]*transform:\s*translateY\(-50%\)/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.site-header\s*\{[\s\S]*min-height:\s*3\.55rem[\s\S]*\.site-header \.header-brand-mark\s*\{[\s\S]*height:\s*2\.55rem/);
  assert.match(css, /Final modal brand and desktop contact refinements/);
  assert.match(css, /\.card-brand-mark \.brand-logo-img\s*\{[\s\S]*filter:\s*brightness\(0\) contrast\(1\.08\)/);
  assert.match(css, /\.contact-call \.phone-line-icon\s*\{[\s\S]*stroke-width:\s*1\.08/);
  assert.match(css, /@media \(min-width:\s*761px\)[\s\S]*\.contact-phone-cell\s*\{[\s\S]*padding-left:\s*1rem/);
  assert.match(css, /Final cross-device consistency for menu card, owls, and phone CTA/);
  assert.match(css, /\.tripadvisor-badge b\s*\{[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /\.card-brand-mark \.brand-logo-img\s*\{[\s\S]*object-fit:\s*contain[\s\S]*filter:\s*brightness\(0\) contrast\(1\.08\)/);
  assert.match(css, /\.contact-section \.contact-actions \.contact-call \.phone-line-icon,[\s\S]*\.contact-section \.contact-actions \.contact-call \.phone-line-icon path\s*\{[\s\S]*fill:\s*none[\s\S]*stroke:\s*currentColor/);
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.contact-section \.contact-actions \.contact-call \.phone-line-icon,[\s\S]*\.contact-section \.contact-actions \.contact-call \.phone-line-icon path\s*\{[\s\S]*fill:\s*none[\s\S]*stroke:\s*currentColor/);
  assert.doesNotMatch(css, /#1fbf62|whatsapp-icon-bg|whatsapp-icon-ring/);
  assert.doesNotMatch(css, /review-links-summary a:hover[\s\S]{0,220}background:\s*var\(--ink\)/);
  assert.match(css, /\.map-frame/);
  assert.match(css, /saturate\(1\.18\)/);
  assert.match(css, /@import url\("https:\/\/fonts\.googleapis\.com/);
  assert.match(script, /whatsappNumber = "393899215920"/);
  assert.match(script, /"cta\.menu": "Scopri il nostro menù"/);
  assert.match(script, /"card\.food": "Menù"/);
  assert.match(script, /convivialità/);
  assert.match(script, /"location\.exterior": "L'esterno"/);
  assert.match(script, /"reviews\.title": "Cosa dicono di noi"/);
  assert.match(script, /"contacts\.title": "Contatti"/);
  assert.match(script, /"form\.time": "Orario"/);
  assert.match(script, /Ciao La Taverna, sono \$\{name\} e vorrei prenotare un tavolo/);
  assert.match(script, /per il giorno \$\{formattedDate\}/);
  assert.match(script, /alle \$\{time\}/);
  assert.match(script, /https:\/\/wa\.me\/\$\{whatsappNumber\}/);
  assert.match(script, /setStickyBookTheme/);
  assert.match(script, /footerSection/);
  assert.match(script, /is-on-light/);
  assert.match(script, /setupCarousel/);
  assert.match(favicon, /<svg/);
  assert.doesNotMatch(css, /hero-verve|dish-0|location-0|_sites-preview|codex-preview/i);
  assert.doesNotMatch(script, /convivialita|Scopri il nostro menu|Il nostro<br><em>menu\.<\/em>/);
  assert.doesNotMatch(script, /Verve|393465874048|mailto:\$\{contactEmail\}|Richiesta:|Request:|Data:|Guests:|Recensioni aggiornate|Updated reviews/i);
});
